main: cc.carm.plugin.scriptitems.Main
name: ScriptItems

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - CarmJos

softdepend:
  - PlaceholderAPI

api-version: 1.13
folia-supported: true

commands:
  "scriptitems":
    aliases:
      - sitems
    usage: "/scriptitems help"
    description: "ScriptItems 的主指令。"
    permission: "ScriptItems.admin"